// The definitions file, assets/progressEvidence.json — the whole progress
// evidence registry, and what the web content builder tool writes. The game
// loads it at startup, so a record created in the tool needs no code change to
// become real progress evidence.
//
// The file is stubbed per test with page.route rather than written to disk:
// these tests run in parallel with everything else, and a real write would be
// visible to any other spec that happened to load the page mid-run. Stubbing it
// also lets these tests define a tiny registry of their own instead of working
// around the 31 real definitions.
const { test, expect } = require("@playwright/test");
const {
  clickNewGame,
  openNoticeboard,
  openProgressEvidenceEnvelope,
  progressEvidenceCards,
  progressEvidenceWindow,
  readProgressEvidence,
  readProgressEvidenceEntry,
  startNewGame,
} = require("../../support/game-helpers");

const GENERATED_IMAGE_PATH = "./assets/photos/progressEvidenceImages/00001.png";

function generatedDefinition(overrides = {}) {
  return {
    progressEvidenceId: "09001",
    service: "zoomsearch",
    itemId: "pw-generated-record",
    label: "Generated By The Builder Tool",
    imagePath: GENERATED_IMAGE_PATH,
    progressEvidenceActivated: false,
    progressEvidenceDeveloperEnabled: false,
    ...overrides,
  };
}

// Must be called before the first navigation, so the game's startup fetch of
// assets/progressEvidence.json sees the stub.
async function stubGeneratedDefinitions(page, definitions) {
  await page.route("**/assets/progressEvidence.json", (route) => route.fulfill({
    status: 200,
    contentType: "application/json; charset=utf-8",
    body: JSON.stringify({ definitions }),
  }));
}

function cardIds(page) {
  return progressEvidenceCards(page).evaluateAll(
    (cards) => cards.map((card) => card.dataset.progressEvidenceId)
  );
}

test("a generated definition joins the registry with both of its flags", async ({ page }) => {
  await stubGeneratedDefinitions(page, [generatedDefinition({ progressEvidenceDeveloperEnabled: true })]);
  await startNewGame(page);

  expect(await readProgressEvidenceEntry(page, "09001")).toMatchObject({
    progressEvidenceId: "09001",
    service: "zoomsearch",
    itemId: "pw-generated-record",
    label: "Generated By The Builder Tool",
    imagePath: GENERATED_IMAGE_PATH,
    progressEvidenceActivated: false,
    progressEvidenceDeveloperEnabled: true,
  });

  // Developer-enabled but not activated is still hidden, exactly as for a
  // shipped item.
  await openNoticeboard(page);
  await openProgressEvidenceEnvelope(page);
  await expect(progressEvidenceCards(page)).toHaveCount(0);
});

test("a generated definition marked activated appears in the envelope immediately", async ({ page }) => {
  await stubGeneratedDefinitions(page, [generatedDefinition({
    progressEvidenceActivated: true,
    progressEvidenceDeveloperEnabled: true,
  })]);
  await startNewGame(page);

  // "In the envelope immediately" means the id is in the persistent collection
  // from the start, without the player doing anything.
  expect(await readProgressEvidence(page)).toEqual(["09001"]);

  await openNoticeboard(page);
  await openProgressEvidenceEnvelope(page);
  expect(await cardIds(page)).toEqual(["09001"]);

  // And it uses the image the tool's photo picker chose, not the
  // [progressEvidenceId].png convention.
  const image = progressEvidenceWindow(page).locator(".progress-evidence-card-image");
  await expect(image).toHaveAttribute("src", GENERATED_IMAGE_PATH);
  await expect.poll(() => image.evaluate((element) => element.naturalWidth)).toBeGreaterThan(0);
});

test("an activated generated definition still needs the developer flag to be shown", async ({ page }) => {
  await stubGeneratedDefinitions(page, [generatedDefinition({
    progressEvidenceActivated: true,
    progressEvidenceDeveloperEnabled: false,
  })]);
  await startNewGame(page);

  expect(await readProgressEvidence(page)).toEqual(["09001"]);

  await openNoticeboard(page);
  await openProgressEvidenceEnvelope(page);
  await expect(progressEvidenceCards(page)).toHaveCount(0);
});

test("an authored activation survives starting a new game", async ({ page }) => {
  await stubGeneratedDefinitions(page, [generatedDefinition({
    progressEvidenceActivated: true,
    progressEvidenceDeveloperEnabled: true,
  })]);
  await startNewGame(page);

  await page.keyboard.press("Escape");
  await clickNewGame(page);

  // A new game clears the player's own progress, but "in the envelope
  // immediately" is a property of the item, so it is seeded again.
  expect(await readProgressEvidence(page)).toEqual(["09001"]);
});

test("a duplicate progressEvidenceId is refused rather than redefining the first", async ({ page }) => {
  await stubGeneratedDefinitions(page, [
    generatedDefinition({ progressEvidenceDeveloperEnabled: true }),
    generatedDefinition({
      // Same id, different record: the file has been hand-edited badly, or two
      // injections raced the allocator.
      itemId: "pw-imposter-record",
      label: "Imposter",
      progressEvidenceActivated: true,
      progressEvidenceDeveloperEnabled: true,
    }),
  ]);
  await startNewGame(page);

  // The first definition holds the id; the second is dropped, and its claim to
  // be already activated goes with it.
  expect(await readProgressEvidenceEntry(page, "09001")).toMatchObject({
    itemId: "pw-generated-record",
    label: "Generated By The Builder Tool",
    progressEvidenceActivated: false,
  });
  expect(await readProgressEvidence(page)).toEqual([]);
});

test("the real definitions file registers every website and fax with a service-coded id", async ({ page }) => {
  // No stub: this is the file the game actually ships with.
  await startNewGame(page);

  const entries = await page.evaluate(() => window.progressEvidenceDeveloperTools.getProgressEvidenceEntries());
  const controlDigitByService = {
    zoomsearch: "0",
    library: "1",
    police: "2",
    archives: "3",
    standalone: "4",
    facsimile: "5",
  };

  expect(entries.length).toBeGreaterThan(0);
  entries.forEach((entry) => {
    // Five digits, and the leading one names the entry's own service.
    expect(entry.progressEvidenceId).toMatch(/^\d{5}$/);
    expect(entry.progressEvidenceId.charAt(0)).toBe(controlDigitByService[entry.service]);
  });

  // Ids are unique across the whole registry, not just within a service.
  const ids = entries.map((entry) => entry.progressEvidenceId);
  expect(new Set(ids).size).toBe(ids.length);

  // Every definition names its image explicitly, on the [progressEvidenceId].png
  // convention, rather than leaning on the manager's fallback.
  entries.forEach((entry) => {
    expect(entry.imagePath).toBe(`./assets/photos/progressEvidenceImages/${entry.progressEvidenceId}.png`);
  });

  // Every service is represented, so nothing was missed in the backfill.
  expect(new Set(entries.map((entry) => entry.service))).toEqual(
    new Set(Object.keys(controlDigitByService))
  );
});
